apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  hub: harbor.cloud2go.cn/istio
  addonComponents:
    prometheus:
      enabled: false
    prometheusOperator:
      enabled: true
    istiocoredns:
      enabled: true
    kiali:
      enabled: true
  components:
    egressGateways:
      - name: istio-egressgateway
        enabled: true
  values:
    global:
      meshExpansion:
        enabled: true
      # Provides dns resolution for global services
      podDNSSearchNamespaces:
        - global
      multiCluster:
        enabled: true
      controlPlaneSecurityEnabled: true
    gateways:
      istio-egressgateway:
        env:
          # Needed to route traffic via egress gateway if desired.
          ISTIO_META_REQUESTED_NETWORK_VIEW: "external"
    kiali:
      createDemoSecret: true
      hub: harbor.cloud2go.cn/istio
    istiocoredns:
      coreDNSImage: harbor.cloud2go.cn/istio/coredns
      coreDNSPluginImage: harbor.cloud2go.cn/istio/coredns-plugin:0.2-istio-1.1
    prometheusOperator:
      createPrometheusResource: true
    prometheus:
      hub: harbor.cloud2go.cn/istio
      security:
        enabled: false
      provisionPrometheusCert: false