kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: sidecar-inject
subjects:
  - kind: ServiceAccount
    name: sidecar-inject-service-account
    namespace: istio-system
roleRef:
  kind: ClusterRole
  name: sidecar-inject
  apiGroup: rbac.authorization.k8s.io