kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default
  namespace: istio-system
subjects:
  - kind: ServiceAccount
    name: default
    namespace: istio-system
roleRef:
  kind: Role
  name: default
  apiGroup: rbac.authorization.k8s.io