apiVersion: v1
kind: Service
metadata:
  name: sidecar-injector
  namespace: istio-system
  labels:
    app: sidecar-injector
spec:
  ports:
    - name: https
      port: 443
      targetPort: 443
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: sidecar-injector